"""add_qa_metrics_tables

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-05 12:52:02.713109
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0011'
down_revision: Union[str, None] = '0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Schema creation if not exists
    op.execute("CREATE SCHEMA IF NOT EXISTS qachub;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_suites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_object', sa.String(), nullable=False),
    sa.Column('test_type', sa.String(), nullable=False),
    sa.Column('suite_version', sa.String(), nullable=False),
    sa.Column('owner_team', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_object', 'test_type', 'suite_version', name='uix_qachub_suite_def'),
    schema='qachub'
    )
    op.create_table('test_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('suite_id', sa.UUID(), nullable=False),
    sa.Column('scenario_qty', sa.Integer(), nullable=True),
    sa.Column('passed_scenario', sa.Integer(), nullable=True),
    sa.Column('failed_scenario', sa.Integer(), nullable=True),
    sa.Column('broken_scenario', sa.Integer(), nullable=True),
    sa.Column('timestamp_start', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('timestamp_end', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('env', sa.Enum('DEV', 'UAT', 'PROD', name='env_enum', schema='qachub'), nullable=True),
    sa.Column('trigger_type', sa.Enum('MANUAL', 'CRON', 'CI_PIPELINE', name='trigger_type_enum', schema='qachub'), nullable=True),
    sa.Column('test_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['suite_id'], ['qachub.test_suites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='qachub'
    )
    op.create_index('ix_qachub_test_runs_env', 'test_runs', ['env'], unique=False, schema='qachub')
    op.create_index(op.f('ix_qachub_test_runs_suite_id'), 'test_runs', ['suite_id'], unique=False, schema='qachub')
    op.create_index('ix_qachub_test_runs_timestamp_start', 'test_runs', ['timestamp_start'], unique=False, schema='qachub')
    op.create_table('test_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('allure_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PASSED', 'FAILED', 'BROKEN', 'SKIPPED', name='scenario_status_enum', schema='qachub'), nullable=True),
    sa.Column('scenario_name', sa.String(), nullable=True),
    sa.Column('allure_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['qachub.test_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='qachub'
    )
    op.create_index(op.f('ix_qachub_test_executions_run_id'), 'test_executions', ['run_id'], unique=False, schema='qachub')
    op.create_index('ix_qachub_test_executions_status', 'test_executions', ['status'], unique=False, schema='qachub')

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_qachub_test_executions_status', table_name='test_executions', schema='qachub')
    op.drop_index(op.f('ix_qachub_test_executions_run_id'), table_name='test_executions', schema='qachub')
    op.drop_table('test_executions', schema='qachub')
    op.drop_index('ix_qachub_test_runs_timestamp_start', table_name='test_runs', schema='qachub')
    op.drop_index(op.f('ix_qachub_test_runs_suite_id'), table_name='test_runs', schema='qachub')
    op.drop_index('ix_qachub_test_runs_env', table_name='test_runs', schema='qachub')
    op.drop_table('test_runs', schema='qachub')
    op.drop_table('test_suites', schema='qachub')
    # Clear ENUMS
    op.execute("DROP TYPE IF EXISTS qachub.env_enum;")
    op.execute("DROP TYPE IF EXISTS qachub.trigger_type_enum;")
    op.execute("DROP TYPE IF EXISTS qachub.scenario_status_enum;")
    # ### end Alembic commands ###