"""add TAS columns in test metrics 

Revision ID: 0014
Revises: 0013
Create Date: 2026-10-02 12:53:13.392315
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0014'
down_revision: Union[str, None] = '0013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE qachub.trigger_type_enum ADD VALUE 'TAS'")
    op.execute("ALTER TYPE qachub.trigger_type_enum ADD VALUE 'QA_GATE'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_runs', sa.Column('test_origin', sa.String(), nullable=True), schema='qachub')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("ALTER TYPE qachub.trigger_type_enum RENAME TO trigger_type_enum_old")
    op.execute("CREATE TYPE qachub.trigger_type_enum AS ENUM ('MANUAL', 'CRON', 'CI_PIPELINE')")
    op.execute(
        "ALTER TABLE qachub.test_runs ALTER COLUMN trigger_type "
        "TYPE qachub.trigger_type_enum "
        "USING trigger_type::text::qachub.trigger_type_enum"
    )
    op.execute("DROP TYPE qachub.trigger_type_enum_old")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_runs', 'test_origin', schema='qachub')
    # ### end Alembic commands ###
   
